In [1]:
!pip install -e .

Obtaining file:///autofs/nccs-svm1_home1/pemami/Workspace/esm_one_hot
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
  Building editable for fair-esm-one-hot (pyproject.toml) ... done
  Created wheel for fair-esm-one-hot: filename=fair_esm_one_hot-0.4.0-0.editable-py3-none-any.whl size=4223 sha256=da68b4e021ba528b840804af4f71c72429561e7f82e6fa56ba3b0b7373acb38f
  Stored in directory: /tmp/pip-ephem-wheel-cache-vvo13avw/wheels/65/4b/8a/74ad85373edc08136804be24c1ae131e6f9b9e5bfc8799a4ad
Successfully built fair-esm-one-hot
  Attempting uninstall: fair-esm-one-hot
    Found existing installation: fair-esm-one-hot 0.4.0
    Uninstalling fair-esm-one-hot-0.4.0:
      Successfully uninstalled fair-esm-one-hot-0.4.0


In [2]:
import torch
import esm_one_hot
from esm_one_hot import pretrained

%load_ext autoreload
%autoreload 2

In [9]:
msa_tran, msa_tran_alphabet = pretrained.esm_msa1b_t12_100M_UR50S()
msa_tran_alphabet.all_toks

['<cls>',
 '<pad>',
 '<eos>',
 '<unk>',
 'L',
 'A',
 'G',
 'V',
 'S',
 'E',
 'R',
 'T',
 'I',
 'D',
 'P',
 'K',
 'Q',
 'N',
 'F',
 'Y',
 'M',
 'H',
 'W',
 'C',
 'X',
 'B',
 'U',
 'Z',
 'O',
 '.',
 '-',
 '<null_1>',
 '<mask>']

In [3]:
esm2, esm2_alphabet = pretrained.esm2_t30_150M_UR50D()
esm2_alphabet.all_toks

['<cls>',
 '<pad>',
 '<eos>',
 '<unk>',
 'L',
 'A',
 'G',
 'V',
 'S',
 'E',
 'R',
 'T',
 'I',
 'D',
 'P',
 'K',
 'Q',
 'N',
 'F',
 'Y',
 'M',
 'H',
 'W',
 'C',
 'X',
 'B',
 'U',
 'Z',
 'O',
 '.',
 '-',
 '<null_1>',
 '<mask>']

In [4]:
test_protein = [
    ('test1', 'MSDF'), ('test2', 'MPAF')
]

batch_converter = esm2_alphabet.get_batch_converter()
labels, strs, one_hot_toks = batch_converter(test_protein)
one_hot_toks

tensor([[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
  

In [5]:
one_hot_tokens_with_grad = one_hot_toks.requires_grad_()
out = esm2(one_hot_tokens_with_grad)["logits"].mean()
torch.autograd.grad(out, one_hot_tokens_with_grad)

(tensor([[[-5.2698e-03, -1.1887e-02,  7.3359e-03, -1.2031e-02,  9.7980e-03,
            1.6777e-04,  2.3783e-02, -3.3990e-03,  8.2630e-03,  2.3936e-02,
            2.4337e-02, -6.9393e-03,  9.5549e-03,  3.2974e-02,  1.1873e-02,
            1.6436e-02,  4.1061e-03,  1.1740e-02,  2.0664e-02,  2.2837e-03,
            2.1561e-02,  4.5841e-03,  2.9053e-03,  1.0535e-02,  1.1112e-02,
            5.4582e-03,  6.0328e-03,  8.3675e-03,  2.5609e-03,  2.6188e-03,
            3.0409e-03,  1.9592e-03, -1.1888e-02],
          [ 3.5781e-02,  3.1107e-02,  6.4021e-02,  3.1746e-02, -2.2688e-02,
           -2.3243e-02,  1.9440e-02, -5.2096e-02,  3.3468e-02,  7.7185e-02,
            1.5640e-02,  4.6157e-03,  9.5460e-03,  8.8880e-02,  3.5780e-02,
            5.3489e-02,  1.4562e-02,  5.1913e-02,  2.4992e-02,  6.0478e-02,
           -5.5724e-03,  4.9806e-02, -2.0380e-03, -3.7201e-02,  9.6823e-03,
            8.3758e-03,  1.6473e-02,  1.4016e-02,  4.2343e-03,  4.5924e-03,
            5.5805e-03,  4.9242e-03, 

In [10]:
test_protein = [
    [('test1', 'MSDF'), ('test2', 'MPAF')]
]

batch_converter = msa_tran_alphabet.get_batch_converter()
labels, strs, one_hot_toks = batch_converter(test_protein)
one_hot_toks

tensor([[[[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
           0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

         [[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0

In [11]:
msa_tran(one_hot_toks)

{'logits': tensor([[[[-1.2648e+01, -2.1189e+01, -2.1269e+01, -2.1487e+01, -5.6530e-01,
             1.0113e+00, -2.7753e-01,  5.1075e-01,  1.9523e+00,  2.9464e-01,
             1.1187e+00,  4.3135e-01, -9.8967e-01,  2.4738e+00, -1.7339e+00,
             1.8718e-01,  1.7503e-01,  1.5213e-01, -1.3416e+00, -7.3866e-01,
            -8.3924e-01,  1.2596e-01, -2.6412e+00,  1.4776e-01, -2.6773e+00,
            -8.8503e+00, -8.9729e+00, -9.9965e+00, -1.2769e+01, -1.4731e+01,
            -2.7506e+00, -1.4650e+01, -1.5541e+01],
           [-1.5852e+01, -1.4309e+01, -1.4323e+01, -1.4287e+01,  3.8991e+00,
            -1.9077e-01, -1.2698e+00,  2.3979e+00,  2.7993e-01, -1.2845e+00,
             4.4707e-01,  1.2831e+00,  3.3778e+00, -1.1155e+00, -1.4912e+00,
            -3.0508e-01,  3.7757e-01, -8.2696e-02,  9.5674e-01,  8.6257e-02,
             1.0625e+01, -8.5940e-01, -3.1142e-02, -8.8138e-01, -1.2384e-01,
            -6.6834e+00, -4.3859e+00, -8.7489e+00, -1.1077e+01, -1.3849e+01,
            -1

In [12]:
one_hot_tokens_with_grad = one_hot_toks.requires_grad_()
out = msa_tran(one_hot_tokens_with_grad)["logits"].mean()
torch.autograd.grad(out, one_hot_tokens_with_grad)

(tensor([[[[-3.0176e-03,  5.0658e-02,  5.1509e-02,  5.1290e-02, -9.7726e-03,
            -4.4023e-02,  2.5610e-02, -4.0802e-02,  2.1563e-02,  1.8786e-02,
            -2.6255e-02, -7.0165e-03, -1.2416e-02,  1.1046e-02,  4.7415e-03,
            -2.8709e-02,  3.8896e-03,  1.4030e-03, -9.2880e-03, -1.2062e-03,
            -1.5061e-02, -2.2774e-02,  1.2993e-02, -5.1096e-02,  9.0028e-02,
             2.9580e-02,  2.1864e-02,  2.5493e-02,  2.2663e-02,  2.3388e-02,
             4.1855e-02,  1.8319e-02,  2.4889e-02],
           [ 5.5021e-02, -1.3385e-02, -1.8966e-02, -1.2731e-02, -2.4456e-02,
             2.2325e-02, -1.9095e-02, -5.8543e-02,  2.7968e-02, -2.0573e-03,
            -3.3984e-02, -6.3946e-03, -2.3503e-02,  3.3542e-02,  8.0198e-03,
            -2.9183e-02,  1.5743e-02,  2.5813e-02, -2.1868e-02, -1.9306e-02,
            -5.8066e-02, -2.4950e-02, -1.1074e-01, -3.9870e-02,  4.3330e-02,
            -4.3308e-02, -4.4980e-02, -5.2048e-02, -4.9213e-02, -5.7502e-02,
            -8.7358e-03,